export   const CONTEXT_MENU_KIND = {
    ADD:'ADD_ITEM',
    REMOVE:"REMOVE_ITEM",
    SETTINGS:'TOOGLE_SETTINGS',
    CLOSE_SETTINGS: 'CLOSE_SETTINGS',
    MAKE:'GENERATE_CSS_CODE',
    DIVIDE:'DIVIDER',
    ABOUT:'ABOUT',
    HIGHLIGHT:'HIGHLIGHT_GRID'
  }